// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cydggxzdgsrwnhzwwbzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5ZGdneHpkZ3Nyd25oend3YnpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NzcwMDQsImV4cCI6MjA3NDE1MzAwNH0.3ILsGUD6svvv8qaUxrNWOCu4rcjNhuRNNngj_i7yiYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});